version: '3'

services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/app:/src
    tty: true
    environment:
      - NODE_ENV=development